export const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.PENDING]: 'Pending',
  [ORDER_STATUS.CONFIRMED]: 'Confirmed',
  [ORDER_STATUS.IN_PROGRESS]: 'In Progress',
  [ORDER_STATUS.COMPLETED]: 'Completed',
  [ORDER_STATUS.DELIVERED]: 'Delivered',
  [ORDER_STATUS.CANCELLED]: 'Cancelled',
};

export const ORDER_STATUS_COLORS = {
  [ORDER_STATUS.PENDING]: '#FFB300',
  [ORDER_STATUS.CONFIRMED]: '#2196F3',
  [ORDER_STATUS.IN_PROGRESS]: '#6C63FF',
  [ORDER_STATUS.COMPLETED]: '#00C853',
  [ORDER_STATUS.DELIVERED]: '#00D9FF',
  [ORDER_STATUS.CANCELLED]: '#FF3D00',
};
