export const ORDER_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  DELIVERED: 'DELIVERED',
};

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.PENDING]: 'Pending',
  [ORDER_STATUS.IN_PROGRESS]: 'In Progress',
  [ORDER_STATUS.PENDING_APPROVAL]: 'Pending Approval',
  [ORDER_STATUS.DELIVERED]: 'Delivered',
};

export const ORDER_STATUS_COLORS = {
  [ORDER_STATUS.PENDING]: '#FFB300',
  [ORDER_STATUS.IN_PROGRESS]: '#6C63FF',
  [ORDER_STATUS.PENDING_APPROVAL]: '#FF9800',
  [ORDER_STATUS.DELIVERED]: '#00C853',
};
