export const ROUTES = {
  HOME: '/',
  SERVICES: '/services',
  SERVICE_DETAIL: '/services/:slug',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  DASHBOARD_ORDERS: '/dashboard/orders',
  DASHBOARD_CHAT: '/dashboard/chat',
  DASHBOARD_REVIEWS: '/dashboard/reviews',
  DASHBOARD_PROFILE: '/dashboard/profile',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:slug',
  CONTACT: '/contact',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_SERVICES: '/admin/services',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_CHAT: '/admin/chat',
  ADMIN_BLOGS: '/admin/blogs',
  ADMIN_REVIEWS: '/admin/reviews',
};
