export const SERVICES_DATA = [
  {
    id: 'static-1',
    title: 'Shopify Store Setup',
    slug: 'shopify-store-setup',
    shortDesc: 'Full store setup with theme, products, and payment integration.',
    description: 'Complete Shopify store setup from scratch. We handle everything from theme selection to product upload, payment gateway integration, and domain configuration.',
    price: 499,
    icon: '🏪',
    features: ['Theme installation & customization', 'Product upload (up to 50)', 'Payment gateway setup', 'Domain configuration', 'Basic SEO setup'],
    isFeatured: true,
    sortOrder: 1,
  },
  {
    id: 'static-2',
    title: 'Custom Theme Development',
    slug: 'custom-theme-development',
    shortDesc: 'Unique, high-performance custom Shopify theme.',
    description: 'Bespoke Shopify theme built from scratch using Shopify 2.0 architecture. Fully responsive, optimized for speed, and tailored to your brand.',
    price: 1999,
    icon: '🎨',
    features: ['Custom design from scratch', 'Shopify 2.0 architecture', 'Mobile-first responsive', 'Speed optimized', 'Section-based customization'],
    isFeatured: true,
    sortOrder: 2,
  },
  {
    id: 'static-3',
    title: 'Shopify SEO Optimization',
    slug: 'shopify-seo-optimization',
    shortDesc: 'Boost rankings and organic traffic with expert SEO.',
    description: 'Comprehensive SEO audit and optimization for your Shopify store. Improve rankings, drive organic traffic, and increase conversions.',
    price: 799,
    icon: '🔍',
    features: ['Full SEO audit', 'Meta tags optimization', 'Schema markup', 'Speed optimization', 'Monthly reporting'],
    isFeatured: true,
    sortOrder: 3,
  },
  {
    id: 'static-4',
    title: 'App Integration & Development',
    slug: 'app-integration-development',
    shortDesc: 'Custom apps and integrations for your store.',
    description: 'Custom Shopify app development and third-party app integrations to extend your store functionality.',
    price: 1499,
    icon: '⚡',
    features: ['Custom app development', 'Third-party integrations', 'API development', 'Webhook setup', 'Testing & deployment'],
    isFeatured: false,
    sortOrder: 4,
  },
  {
    id: 'static-5',
    title: 'Store Migration',
    slug: 'store-migration',
    shortDesc: 'Migrate to Shopify from any platform seamlessly.',
    description: 'Seamless migration from WooCommerce, Magento, BigCommerce, or any platform to Shopify with zero data loss.',
    price: 999,
    icon: '🔄',
    features: ['Data migration', 'URL redirects', 'SEO preservation', 'Design recreation', 'Post-migration support'],
    isFeatured: false,
    sortOrder: 5,
  },
  {
    id: 'static-6',
    title: 'Conversion Rate Optimization',
    slug: 'conversion-rate-optimization',
    shortDesc: 'Maximize revenue with data-driven optimization.',
    description: 'Data-driven CRO strategies to maximize your store revenue. A/B testing, UX improvements, and checkout optimization.',
    price: 1299,
    icon: '📈',
    features: ['Conversion audit', 'A/B testing setup', 'Checkout optimization', 'UX improvements', 'Analytics setup'],
    isFeatured: false,
    sortOrder: 6,
  },
];

export const REVIEWS_DATA = [
  {
    id: 'review-1',
    rating: 5,
    comment: 'Absolutely transformed our Shopify store! The custom theme they built is stunning and our conversion rate increased by 40% within the first month. Highly recommend their services.',
    name: 'Sarah Mitchell',
    role: 'CEO, LuxeBrand Co.',
    user: null,
  },
  {
    id: 'review-2',
    rating: 5,
    comment: 'Professional, responsive, and incredibly talented. They migrated our entire WooCommerce store to Shopify without any downtime. The attention to detail was remarkable.',
    name: 'James Rodriguez',
    role: 'Founder, TechGear Store',
    user: null,
  },
  {
    id: 'review-3',
    rating: 5,
    comment: 'The SEO optimization service was a game-changer. Our organic traffic increased by 200% in just three months. Worth every penny invested.',
    name: 'Emily Chen',
    role: 'Marketing Director, FashionHub',
    user: null,
  },
  {
    id: 'review-4',
    rating: 5,
    comment: 'Outstanding app development work. The custom features they built streamlined our operations and saved us hours of manual work every week.',
    name: 'Michael Thompson',
    role: 'Operations Manager, FreshFoods',
    user: null,
  },
  {
    id: 'review-5',
    rating: 4,
    comment: 'Great communication throughout the project. They delivered our store setup ahead of schedule and the end result exceeded our expectations.',
    name: 'Lisa Park',
    role: 'Owner, BeautyEssentials',
    user: null,
  },
  {
    id: 'review-6',
    rating: 5,
    comment: 'The CRO audit they performed uncovered opportunities we never knew existed. Our revenue has grown 60% since implementing their recommendations.',
    name: 'David Wilson',
    role: 'Co-founder, SportsPro',
    user: null,
  },
];

export const BLOG_DATA = [
  {
    id: 'blog-1',
    title: '10 Tips to Optimize Your Shopify Store Speed',
    slug: '10-tips-optimize-shopify-store-speed',
    excerpt: 'Learn proven strategies to make your Shopify store lightning fast and improve conversion rates.',
    content: 'Store speed directly impacts conversion rates. Studies show that a 1-second delay can reduce conversions by 7%.',
    tags: ['Performance', 'Shopify', 'Optimization'],
    publishedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'blog-2',
    title: 'Shopify 2.0: Everything You Need to Know',
    slug: 'shopify-2-everything-you-need-to-know',
    excerpt: 'A comprehensive guide to Shopify 2.0 features and how to leverage them for your store.',
    content: 'Shopify 2.0 represents a major upgrade introducing sections on every page, app blocks, and metafields.',
    tags: ['Shopify 2.0', 'Guide', 'Development'],
    publishedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'blog-3',
    title: 'How to Choose the Right Shopify Theme for Your Brand',
    slug: 'choose-right-shopify-theme',
    excerpt: 'Selecting the perfect theme is crucial for your brand identity and store performance.',
    content: 'Your Shopify theme is the foundation of your online store. Here is how to pick the right one.',
    tags: ['Themes', 'Branding', 'Shopify'],
    publishedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const PROJECTS_DATA = [
  {
    id: 'project-1',
    title: 'SpaCeylon',
    category: 'Custom Theme',
    description: 'Premium ayurvedic luxury brand from Sri Lanka with an elegant Shopify storefront featuring rich product storytelling, multi-currency support, and a refined checkout experience.',
    image: null,
    tags: ['Shopify 2.0', 'Custom Theme', 'Luxury'],
    liveUrl: 'https://spaceylon.ae/',
    results: ['+280% Conversions', '1.4s Load Time', '35K+ Monthly Visitors'],
  },
  {
    id: 'project-2',
    title: 'Brentwood General Store',
    category: 'Store Setup',
    description: 'Complete Shopify store for a charming general store offering curated home goods, pantry items, and gifts with a warm, community-focused brand experience.',
    image: null,
    tags: ['Store Setup', 'Home & Lifestyle', 'Curated'],
    liveUrl: 'https://www.brentwoodgeneralstore.com/',
    results: ['200+ Products', '4.9 Star Rating', '25K+ Customers'],
  },
  {
    id: 'project-3',
    title: 'Derma Me',
    category: 'Custom Theme',
    description: 'Clean, modern Shopify theme for a professional skincare brand featuring product comparison tools, ingredient highlights, and a streamlined subscription model.',
    image: null,
    tags: ['Custom Theme', 'Beauty', 'Skincare'],
    liveUrl: 'https://dermame.com/',
    results: ['+190% Sales', '2.1s Load Time', '98% Satisfaction'],
  },
  {
    id: 'project-4',
    title: 'UAE Store',
    category: 'Store Setup',
    description: 'Full Shopify store setup for a UAE-based e-commerce brand with RTL support, local payment gateways, and region-specific shipping configurations.',
    image: null,
    tags: ['Store Setup', 'UAE', 'Multi-currency'],
    liveUrl: 'https://uae-store-9402.myshopify.com/',
    results: ['Multi-currency', 'RTL Support', 'Local Payments'],
  },
  {
    id: 'project-5',
    title: 'Goodfair',
    category: 'App Development',
    description: 'Sustainable thrift fashion brand with a unique mystery bundle concept. Custom app for bundle management, size-based inventory, and eco-impact tracking.',
    image: null,
    tags: ['Custom App', 'Sustainable', 'Fashion'],
    liveUrl: 'https://goodfair1.myshopify.com/',
    results: ['50K+ Bundles Sold', '3x Revenue Growth', 'Zero Waste Mission'],
  },
  {
    id: 'project-6',
    title: 'Silk & Willow',
    category: 'Custom Theme',
    description: 'Ethereal Shopify theme for a sustainable wedding textiles brand featuring plant-dyed ribbons and fabrics with artisanal photography and poetic storytelling.',
    image: null,
    tags: ['Custom Theme', 'Wedding', 'Sustainable'],
    liveUrl: 'https://silkandwillow.com/',
    results: ['+220% Conversions', '45K+ Monthly Visitors', '4.9 Star Rating'],
  },
  {
    id: 'project-7',
    title: 'Fly By Jing',
    category: 'SEO & CRO',
    description: 'Bold Shopify store for a Sichuan chili crisp brand with vibrant design, cultural storytelling, and optimized checkout driving strong conversions.',
    image: null,
    tags: ['SEO', 'CRO', 'Food & Beverage'],
    liveUrl: 'https://flybyjing.com/',
    results: ['+300% Organic Traffic', '+95% Conversion Rate', 'Page 1 Rankings'],
  },
  {
    id: 'project-8',
    title: 'Herbivore Botanicals',
    category: 'Custom Theme',
    description: 'Minimalist Shopify theme for an all-natural skincare brand with a muted pastel palette, spa-like aesthetics, and seamless product discovery experience.',
    image: null,
    tags: ['Custom Theme', 'Beauty', 'Natural'],
    liveUrl: 'https://herbivorebotanicals.com/',
    results: ['+175% Sales', '1.8s Load Time', '60K+ Customers'],
  },
  {
    id: 'project-9',
    title: 'Fishwife',
    category: 'Store Setup',
    description: 'Vibrant and playful Shopify store for a premium tinned seafood brand with colorful packaging-inspired design and bold illustrations.',
    image: null,
    tags: ['Store Setup', 'Food & Beverage', 'Branding'],
    liveUrl: 'https://eatfishwife.com/',
    results: ['500+ Products', '$1.5M+ Revenue', '4.8 Star Rating'],
  },
  {
    id: 'project-10',
    title: 'Tentree',
    category: 'App Development',
    description: 'Sustainable apparel brand with custom tree-planting tracker integration. Every purchase plants 10 trees, with progress visible throughout the shopping experience.',
    image: null,
    tags: ['Custom App', 'Sustainable', 'Fashion'],
    liveUrl: 'https://tentree.com/',
    results: ['110M+ Trees Planted', '3x Retention', '4.7 Star Rating'],
  },
  {
    id: 'project-11',
    title: 'Artisaire',
    category: 'Custom Theme',
    description: 'Refined luxury Shopify theme for a wax seal artisan brand with meticulous product photography and interactive customization tools.',
    image: null,
    tags: ['Custom Theme', 'Stationery', 'Luxury'],
    liveUrl: 'https://artisaire.com/',
    results: ['+250% Conversions', '30K+ Monthly Visitors', '99% Satisfaction'],
  },
  {
    id: 'project-12',
    title: 'Venus ET Fleur',
    category: 'SEO & CRO',
    description: 'High-end luxury gifting brand specializing in eternity roses. Dark, moody design with jewelry-store aesthetics and optimized gifting checkout flow.',
    image: null,
    tags: ['SEO', 'CRO', 'Luxury Gifting'],
    liveUrl: 'https://venusetfleur.com/',
    results: ['+400% Organic Traffic', '+120% AOV', 'Featured by Shopify'],
  },
  {
    id: 'project-13',
    title: 'Maguire Shoes',
    category: 'Migration',
    description: 'Seamless platform migration for a Montreal boutique shoe brand. Editorial-quality lookbook design with European-inspired aesthetics.',
    image: null,
    tags: ['Migration', 'Fashion', 'Footwear'],
    liveUrl: 'https://maguireshoes.com/',
    results: ['Zero Downtime', '40% Speed Boost', '2x Mobile Sales'],
  },
  {
    id: 'project-14',
    title: 'Flourist',
    category: 'Store Setup',
    description: 'Elegant Shopify store for a traceable specialty grains brand. Boutique-level visual design for pantry staples with detailed provenance information.',
    image: null,
    tags: ['Store Setup', 'Food & Beverage', 'Organic'],
    liveUrl: 'https://flourist.com/',
    results: ['300+ Products', '25K+ Customers', '4.9 Star Rating'],
  },
  {
    id: 'project-15',
    title: 'Bebemoss',
    category: 'App Development',
    description: 'Handcrafted organic cotton toys brand with B Corp certification. Custom inventory and artisan management system supporting refugee employment.',
    image: null,
    tags: ['Custom App', 'Kids', 'Social Impact'],
    liveUrl: 'https://bebemoss.com/',
    results: ['B Corp Certified', '5K+ Toys Sold', '100% Organic'],
  },
  {
    id: 'project-16',
    title: 'Hiut Denim Co.',
    category: 'Custom Theme',
    description: 'Clean, minimal Shopify theme for a Welsh denim brand built on the philosophy of "Do One Thing Well." Storytelling-focused design with craftsmanship at its core.',
    image: null,
    tags: ['Custom Theme', 'Fashion', 'Denim'],
    liveUrl: 'https://hiutdenim.co.uk/',
    results: ['+160% Sales', '20K+ Monthly Visitors', 'Award-Winning Design'],
  },
];

export const FAQ_DATA = [
  {
    id: 'faq-1',
    question: 'How long does it take to build a Shopify store?',
    answer: 'A standard Shopify store setup typically takes 1-2 weeks. Custom theme development can take 4-8 weeks depending on complexity. We provide detailed timelines during the discovery phase of every project.',
  },
  {
    id: 'faq-2',
    question: 'Do you offer ongoing support after the store is launched?',
    answer: 'Yes! We offer flexible support packages that include maintenance, updates, performance monitoring, and strategic consulting. We are committed to your long-term success.',
  },
  {
    id: 'faq-3',
    question: 'Can you migrate my existing store to Shopify?',
    answer: 'Absolutely. We have extensive experience migrating stores from WooCommerce, Magento, BigCommerce, Wix, and other platforms. We ensure zero data loss, proper URL redirects, and SEO preservation.',
  },
  {
    id: 'faq-4',
    question: 'What makes your services different from other Shopify agencies?',
    answer: 'We combine deep technical expertise with a focus on business results. Every decision we make is driven by data and aimed at maximizing your ROI. Plus, we offer transparent pricing with no hidden fees.',
  },
  {
    id: 'faq-5',
    question: 'Do you build custom Shopify apps?',
    answer: 'Yes, we develop custom public and private Shopify apps tailored to your specific needs. From inventory management to customer engagement tools, we can build solutions that extend your store beyond out-of-the-box capabilities.',
  },
  {
    id: 'faq-6',
    question: 'What is your pricing structure?',
    answer: 'We offer transparent, project-based pricing. Each service has a starting price listed on our services page. For custom projects, we provide detailed quotes after a free discovery call where we understand your requirements.',
  },
  {
    id: 'faq-7',
    question: 'Will my Shopify store be mobile-friendly?',
    answer: 'Absolutely. All our stores are built mobile-first, meaning we design and develop for mobile devices first, then scale up to tablets and desktops. Over 70% of e-commerce traffic comes from mobile, so this is non-negotiable for us.',
  },
  {
    id: 'faq-8',
    question: 'Can you help with Shopify Plus for enterprise needs?',
    answer: 'Yes, we work with Shopify Plus for high-volume merchants who need advanced features like custom checkout, automation with Shopify Flow, wholesale channels, and multi-store management. We can help you evaluate if Plus is right for your business.',
  },
  {
    id: 'faq-9',
    question: 'Do you handle product photography and content creation?',
    answer: 'While our core focus is development and optimization, we partner with professional photographers and content creators. We can coordinate the entire creative process or work with your existing assets to ensure a cohesive brand experience.',
  },
  {
    id: 'faq-10',
    question: 'How do you handle SEO during a store migration?',
    answer: 'SEO preservation is a top priority during migration. We set up 301 redirects for all URLs, migrate meta titles and descriptions, preserve your sitemap structure, and monitor rankings post-launch. Our goal is zero organic traffic loss.',
  },
  {
    id: 'faq-11',
    question: 'Can you integrate third-party apps and services?',
    answer: 'Yes, we integrate all major third-party services including payment gateways (Stripe, PayPal, Klarna), email marketing (Klaviyo, Mailchimp), shipping (ShipStation, Shippo), CRM tools, and analytics platforms. If it has an API, we can connect it.',
  },
  {
    id: 'faq-12',
    question: 'What payment methods can my Shopify store accept?',
    answer: 'Shopify supports 100+ payment gateways worldwide. We can set up Shopify Payments (powered by Stripe), PayPal, Apple Pay, Google Pay, Shop Pay, buy-now-pay-later options like Klarna and Afterpay, and region-specific gateways.',
  },
  {
    id: 'faq-13',
    question: 'Do you offer a satisfaction guarantee?',
    answer: 'We stand behind our work. Each project includes a revision phase where we refine the deliverables based on your feedback. We also offer a 30-day post-launch support period to address any issues that arise after going live.',
  },
  {
    id: 'faq-14',
    question: 'Can I update the store content myself after launch?',
    answer: 'Absolutely! We build every store with content management in mind. Using Shopify 2.0 sections and metafields, you can easily update text, images, products, and page layouts without any coding knowledge. We also provide a training session after launch.',
  },
];

export const PROCESS_STEPS = [
  {
    id: 1,
    icon: '💡',
    title: 'Discovery & Strategy',
    description: 'Deep dive into your business goals, target audience, competitors, and unique selling points to craft a winning e-commerce strategy.',
  },
  {
    id: 2,
    icon: '✏️',
    title: 'Design & Wireframing',
    description: 'Creating stunning UI/UX designs and interactive wireframes that align with your brand and are optimized for maximum conversions.',
  },
  {
    id: 3,
    icon: '💻',
    title: 'Development & Build',
    description: 'Pixel-perfect development using Shopify Liquid, custom JavaScript, and modern best practices ensuring clean, maintainable code.',
  },
  {
    id: 4,
    icon: '🧪',
    title: 'Testing & QA',
    description: 'Rigorous cross-browser, cross-device testing, performance audits, accessibility checks, and user flow validation before launch.',
  },
  {
    id: 5,
    icon: '🚀',
    title: 'Launch & Deployment',
    description: 'Seamless go-live with DNS configuration, SSL setup, analytics integration, and a comprehensive launch checklist for zero issues.',
  },
  {
    id: 6,
    icon: '📊',
    title: 'Support & Growth',
    description: 'Ongoing optimization, feature enhancements, performance monitoring, and strategic advice to continuously grow your revenue.',
  },
];

export const TECHNOLOGIES = [
  { name: 'Shopify', icon: '🛍️' },
  { name: 'Stripe', icon: '💳' },
  { name: 'PayPal', icon: '💰' },
  { name: 'Klarna', icon: '🏦' },
  { name: 'Mailchimp', icon: '📧' },
  { name: 'Zapier', icon: '⚡' },
  { name: 'HubSpot', icon: '🔗' },
  { name: 'GA4', icon: '📊' },
  { name: 'React', icon: '⚛️' },
  { name: 'Node.js', icon: '🟢' },
  { name: 'GraphQL', icon: '◈' },
  { name: 'Figma', icon: '🎨' },
];
